version: '3'

services:
  flask_app:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8989}:8989"
    environment:
      FLASK_APP: app.py
      PORT: ${PORT:-8989}